export const laptopList = [
  {
    id: 1,
    name: "Acer Swift Notebook",
    img: "img/comp-1.png",
    price: 700,
    manufacturer: "Acer",
    info: "Slim, lightweight and stylish, the Swift 3 is the ideal laptop for working on the move. The latest NVIDIA® GPU, Intel® CPU and long battery life are housed inside a choice of displays: an elegantly silver chassis with a 13.5” 3:2 ratio 2256x1504 IPS VertiView Display or the vivid colors of a 14” 16:9 FHD IPS display.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    name: "Dell XPS 9370",
    img: "img/comp-2.png",
    price: 1970,
    manufacturer: "Dell Computer",
    info: "Dell XPS 9370 is a Windows 10 laptop with a 13.30-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Dell XPS 9370 packs 256GB of SSD storage.",
    os: "Ubuntu",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    name: "Acer Aspire",
    img: "img/comp-3.png",
    price: 740,
    manufacturer: "Acer",
    info: "Acer Aspire 3 A31531C7CF is a Windows 10 laptop with a 15.60-inch display that has a resolution of 1366x768 pixels. It is powered by a Celeron Dual Core processor and it comes with 4GB of RAM. The Acer Aspire 3 A31531C7CF packs 500GB of HDD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    name: "Samsung NoteBook 5",
    img: "img/comp-4.png",
    price: 960,
    manufacturer: "Samsung",
    info: "Samsung NoteBook 5 NP550XTA-K01US is a Windows 10 laptop with a 15.60-inch display that has a resolution of 1366x768 pixels. It is powered by a Ryzen 5 processor and it comes with 8GB of RAM. The Samsung NoteBook 5 NP550XTA-K01US packs 1TB of HDD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    name: "Acer Predator Helios ",
    img: "img/comp-5.png",
    price: 1045,
    manufacturer: "Acer",
    info: "Acer Predator Helios 300 G3-571-77QK is a Windows 10 laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i7 processor and it comes with 6GB of RAM. The Acer Predator Helios 300 G3-571-77QK packs 256GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    name: "Lenovo IdeaPad ",
    img: "img/comp-6.png",
    price: 1289,
    manufacturer: "Lenovo Group",
    info: "Lenovo IdeaPad Y700 is a Windows 10 Home laptop with a 17.30-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i7 processor and it comes with 16GB of RAM. The Lenovo IdeaPad Y700 packs 1TB of HDD storage and 128GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    name: "Lenovo ThinkPad ",
    img: "img/comp-7.png",
    price: 1420,
    manufacturer: "Lenovo Group",
    info: "Lenovo ThinkPad is a Windows 10 laptop with a 14.00-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i7 processor and it comes with 12GB of RAM. The Lenovo ThinkPad packs 256GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    name: "Dell XPS 13",
    img: "img/comp-8.png",
    price: 1544,
    manufacturer: "Dell Computer",
    info: "Dell XPS 13 is a Windows 10 laptop with a 13.30-inch display that has a resolution of 3200x1800 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Dell XPS 13 packs 128GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    name: "Acer Predator Triton",
    img: "img/comp-9.png",
    price: 1598,
    manufacturer: "Acer",
    info: "The Acer Predator Helios 700 comes with a 17.3-inch full-HD (1,920x1,080 pixels) IPS display with 144Hz refresh rate and Nvidia G-Sync technology. It is powered by an overclockable 10th-gen Intel Core i9-10980HK ",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    name: "Dell Inspiron Pro",
    img: "img/comp-10.png",
    price: 678,
    manufacturer: "Dell Group",
    info: "Dell Inspiron Pro 3567 is a Windows 10 laptop with a 15.60-inch display that has a resolution of 1366x768 pixels. It is powered by a Core i3 processor and it comes with 8GB of RAM. The Dell Inspiron Pro 3567 packs 1TB of HDD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    name: "Acer Swift 3",
    img: "img/comp-11.png",
    price: 876,
    manufacturer: "Dell Group",
    info: "Acer Swift 3 is a Windows 10 Home laptop with a 14.00-inch display that has a resolution of 1920x1080 pixels. It is powered by a Ryzen 5 processor and it comes with 8GB of RAM. The Acer Swift 3 packs 512GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    name: "Dell Inspirion 14",
    img: "img/comp-12.png",
    price: 1756,
    manufacturer: "Dell Group",
    info: "Dell Inspiron 14 5000 5490 is a Windows 10 laptop with a 14.00-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i3 processor and it comes with 4GB of RAM. The Dell Inspiron 14 5000 5490 packs 512GB of SSD storage.",
    os: "Windows 10",
    inStock: true,
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const laptopSpecs = {
  id: 1,
  name: "Acer Swift Notebook",
  img: "img/comp-1.png",
  price: 700,
  manufacturer: "Acer",
  info: "Slim, lightweight and stylish, the Swift 3 is the ideal laptop for working on the move. The latest NVIDIA® GPU, Intel® CPU and long battery life are housed inside a choice of displays: an elegantly silver chassis with a 13.5” 3:2 ratio 2256x1504 IPS VertiView Display or the vivid colors of a 14” 16:9 FHD IPS display.",
  os: "Windows 10",
  inStock: true,
  inCart: false,
  count: 0,
  total: 0,
};
